#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-hms
Version  : 0.3
Release  : 9
URL      : https://cran.r-project.org/src/contrib/hms_0.3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/hms_0.3.tar.gz
Summary  : Pretty Time of Day
Group    : Development/Tools
License  : GPL-3.0
BuildRequires : clr-R-helpers

%description
hms [![Travis-CI Build Status](https://travis-ci.org/rstats-db/hms.svg?branch=master)](https://travis-ci.org/rstats-db/hms) [![AppVeyor Build Status](https://ci.appveyor.com/api/projects/status/github/rstats-db/hms?branch=master&svg=true)](https://ci.appveyor.com/project/rstats-db/hms) [![Coverage Status](https://img.shields.io/codecov/c/github/rstats-db/hms/master.svg)](https://codecov.io/github/rstats-db/hms?branch=master) [![CRAN\_Status\_Badge](http://www.r-pkg.org/badges/version/hms)](https://cran.r-project.org/package=hms)
======================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

%prep
%setup -q -c -n hms

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1496602104

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1496602104
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library hms
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library hms
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
rm ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library hms
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library hms
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/hms/DESCRIPTION
/usr/lib64/R/library/hms/INDEX
/usr/lib64/R/library/hms/Meta/Rd.rds
/usr/lib64/R/library/hms/Meta/features.rds
/usr/lib64/R/library/hms/Meta/hsearch.rds
/usr/lib64/R/library/hms/Meta/links.rds
/usr/lib64/R/library/hms/Meta/nsInfo.rds
/usr/lib64/R/library/hms/Meta/package.rds
/usr/lib64/R/library/hms/NAMESPACE
/usr/lib64/R/library/hms/NEWS.md
/usr/lib64/R/library/hms/R/hms
/usr/lib64/R/library/hms/R/hms.rdb
/usr/lib64/R/library/hms/R/hms.rdx
/usr/lib64/R/library/hms/help/AnIndex
/usr/lib64/R/library/hms/help/aliases.rds
/usr/lib64/R/library/hms/help/hms.rdb
/usr/lib64/R/library/hms/help/hms.rdx
/usr/lib64/R/library/hms/help/paths.rds
/usr/lib64/R/library/hms/html/00Index.html
/usr/lib64/R/library/hms/html/R.css
